### PR TITLE
Document Update: List of Complex Features Not Supported in Auto Migration

### PR DESCRIPTION
**Pull request by rarandiv**
Adding a list of complex features to the document that are likely not supported during auto migration.

### CODE REVIEW

**Comment by Court72** [comment]
@aditivgupta 

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Court72** [comment]
I sent a Teams message to the author today.

**Comment by aditivgupta** [comment]
We do support CMK and Microsoft Entra ID in auto-migration. The added information is incorrect and hence should not be merged.

**Comment by aditivgupta** [comment]
#please-close

**Pull request closed without merging**
