### PR TITLE
fix: grammer of TypeScript

### PR DESCRIPTION
**Pull request by ry0y4n**

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@sajeetharan

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by sajeetharan — CHANGES_REQUESTED** [review]
Why this change for? does not makes sense.

**Comment by ry0y4n** [comment]
Thank you for your response. 
I noticed that the original code snippet appeared to use syntax that resembles Java, not JavaScript, which could confuse learners. My change corrects it to align with JavaScript (TypeScript) syntax, ensuring consistency and functionality within a JavaScript environment. 
If there’s anything further to clarify, I’d be happy to elaborate.

**Review by sajeetharan — APPROVED** [review]

**Comment by sajeetharan** [comment]
#sign-off

**Comment by ry0y4n** [comment]
@sajeetharan  Thak your for your review.

@ShannonLeavitt Could you please merge this PR?

**Pull request merged**
