### PR TITLE
Update quickstart-terraform.md

### PR DESCRIPTION
**Pull request by patty-chow**
Removing the hacky way to create a cluster since Terraform now supports vCore.

### CODE REVIEW

**Comment by ttorble** [comment]
@gahl-levy 

Can you review the proposed changes?

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by gahl-levy** [comment]
#sign-off

**Review by gahl-levy — APPROVED** [review]

**Comment by patty-chow** [comment]
#sign-off

**Comment by gahl-levy** [comment]
#sign-off

**Pull request merged**
