### PR TITLE
Correct --scope argument to dbs

### PR DESCRIPTION
**Pull request by jjgriff93**
Trying to assign a scope based on an ARM resource id (as currently referenced in the docs) with the `az cosmosdb sql role assignment create` command results in the following error:

```
(BadRequest) Failed to parse the incoming request payload. Exception: System.FormatException: Could not parse property [properties] as [Microsoft.Azure.Documents.Management.Services.ResourceProvider.DataModel.RoleBasedAccessControl.SqlRoleAssignmentProperties] due to exception: System.FormatException: Could not parse property [scope] with value [/subscriptions/c188d79d-f4df-44c8-b9f1-0080b70a00b3/resourceGroups/rg-mlrpreflight-griff/providers/Microsoft.DocumentDB/databaseAccounts/cos-mlrgriff/subscriptions/c188d79d-f4df-44c8-b9f1-0080b70a00b3/resourceGroups/rg-mlrpreflight-griff/providers/Microsoft.DocumentDb/databaseAccounts/cos-mlrgriff] as [Microsoft.Azure.Documents.Management.Services.ResourceProvider.DataModel.RoleBasedAccessControl.FullyQualifiedResourcePath] due to exception: System.FormatException: Expected path segment [dbs] at position [0] but found [subscriptions].
```

I believe this should be `dbs` instead to assign to the database scope, which I've tested and works correctly.

### CODE REVIEW

**Comment by seesharprun** [comment]
@jjgriff93, the Azure CLI and PowerShell commands provide a "shorthand" syntax to assign the scope. Here's a quick breakdown.

First, the scope of a data-plane assignment must be at the account level or lower. So, you can assign scope at the account level, database level, or container level.

For Azure CLI and Azure PowerShell, there's a shorthand syntax where you can omit the full resourceId for the account. However, after your run the command, the output will show that the scope is fully qualified. Here's a few examples:

| Scope | Shorthand | Fully-qualified |
| --- | --- | --- |
| Account | `/` | `/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.DocumentDB/databaseAccounts/<account-name>/` |
| Database | `/dbs/<database-name>` | `/subscriptions/<subscription-id>/resourcegroups/<resource-group-name>/providers/Microsoft.DocumentDB/databaseAccounts/<account-name>/dbs/<database-name>` |
| Container | `/dbs/<database-name>/colls/<container-name>` | `/subscriptions/<subscription-id>/resourcegroups/<resource-group-name>/providers/Microsoft.DocumentDB/databaseAccounts/<account-name>/dbs/<database-name>/colls/<container-name>` |

We intentionally fully qualify the scopes in documentation to try and clear things up. I also personally found that the scope must be fully qualified in REST API, Bicep, and ARM template requests.

So yes, you can use the shorthand in CLI commands, but we documented the fully qualified syntax. You can read more about it in the [scope section of the security glossary](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/security/glossary#scope-azure-cosmos-db-native).

@markjbrown, can you provide additional guidance here?

**Comment by Court72** [comment]
@seesharprun

When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by seesharprun** [comment]
Pending further discussion.

#hold-off

**Comment by markjbrown** [comment]
@seesharprun @jjgriff93 Nothing further to add. The guidance provided in the docs is correct.

**Comment by seesharprun** [comment]
#please-close

**Pull request closed without merging**
