### PR TITLE
Update concepts-maintenance.md (Typo "flexible server"→"Flexible Serv…

### PR DESCRIPTION
**Pull request by hyoshioka0128**
…er")

https://github.com/MicrosoftDocs/azure-databases-docs/blob/main/articles/mysql/flexible-server/concepts-maintenance.md #PingMSFTDocs

### CODE REVIEW

**Comment by Court72** [comment]
@xboxeer

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by hyoshioka0128** [comment]
@shreyaaithal- related #9

**Comment by xboxeer** [comment]
#sign-off

**Review by xboxeer — APPROVED** [review]
Looks good to me

**Pull request merged**
