### PR TITLE
Update Cosmos DB Data Explorer RBAC instructions

### PR DESCRIPTION
**Pull request by sevoku**

### CODE REVIEW

**Comment by Court72** [comment]
@iriaosara

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by iriaosara — APPROVED** [review]

**Comment by Court72** [comment]
@sevoku,

The author has approved your changes. When you're ready for this PR to be merged, select "Ready for review."

image

Thanks!

**Comment by ShannonLeavitt** [comment]
@sevoku is this PR ready to be reviewed and merged?

**Comment by sevoku** [comment]
The original document has been retired with https://github.com/MicrosoftDocs/azure-databases-docs/commit/36f727d53777f2793ffeaaf74d2d3e263db7bd09 and https://github.com/MicrosoftDocs/azure-databases-docs/commit/2b0f57b805abd23d88a6e34dd7b4816ddca93ba0, and I can't find any copy of the Data Explorer RBAC docs. Not sure if that was intended, or whether we need to recover it. Either way... closing this PR for now since the documentation is gone. cc @jawelton74

**Pull request closed without merging**
