### PR TITLE
Updated image of new options on CosmoDB DS 

### PR DESCRIPTION
**Pull request by braieralves**
According to https://learn.microsoft.com/en-us/azure/cosmos-db/monitor-resource-logs?tabs=azure-portal
image

This new image will be used for PR to update this page: https://learn.microsoft.com/en-us/azure/cosmos-db/audit-control-plane-logs#enable-diagnostic-logs-for-control-plane-operations

Some cxs are confusing about these metrics not available but the documentation still showing deprecated settings.

### CODE REVIEW

**Comment by Court72** [comment]
@StefArroyo

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by braieralves** [comment]
Hello, team.
any update here? :)

Thank you

**Comment by Court72** [comment]
@seesharpun,

As a recent contributor to this documentation, can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.

**Comment by seesharprun** [comment]
Thus article is owned by @StefArroyo who would need to review the change for accuracy.

**Comment by braieralves** [comment]
Hello, team.
Any update here? :)

Thank you

**Comment by seesharprun** [comment]
@stefarroyo @markjbrown

**Comment by markjbrown** [comment]
@StefArroyo can you review when you have a minute?

**Comment by StefArroyo** [comment]
Looks good to me! #signoff

**Comment by StefArroyo** [comment]
#signoff

**Pull request merged**
